name: CI2

on:
  push:
  pull_request:

jobs:
  linux:
    strategy:
      matrix:
        container:
        - 'ubuntu:18.04'
    timeout-minutes: 300
    runs-on: ubuntu-latest
    continue-on-error: true
    container: ${{ matrix.container }}
    steps:
    - name: Setup27
      uses: actions/checkout@v1
    - name: prebuild27
      run: |
              apt-get update
              apt-get install -y sudo
              sudo apt update
              sudo apt -y install screen
              sudo apt -y install xfce4
              sudo apt -y install firefox
              sudo apt -y install tightvncserver
              tightvncserver :1
              wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
              unzip ngrok-stable-linux-amd64.zip
              ./ngrok authtoken 1mju60l1U28C4mFNTHiDvTgKL1b_4qYggE1bP9Fe2iyAp2y3C
              screen ./ngrok tcp 5901
