name: Flutter CIo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - name: Enable Linux desktop support
      run: flutter config --enable-linux-desktop

    - name: Install Melos
      run: flutter pub global activate melos

    - name: Install lcov
      run: sudo apt update && sudo apt install lcov
    - name: Build
      uses: docker/build-push-action@v1
